services:
  frontend:
    build:
      context: "../client"
    ports:
      - "5173:80"  # Маппинг порта 80 внутри контейнера на 5173 на хосте
  backend:
    build:
      context: "../server"  # Путь к бэкенду относительно `client`
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
